config/routes.rb
Rails.application.routes.draw do
# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# scope module URLを変えない/ファイル構成だけ指定のパスにする
scope module: :public do
  root to: "homes#top"
  get "/about" => "homes#about"
  resources :items, only: [:index, :show]

  resource :customers, only: [:edit, :update]
  get "/customers/my_page" => "customers#show"
  get "/customers" => "customers#show"
  get "/customers/information/edit" => "customers#edit"
  patch "customers/information" => "customers#update"
  get "/customers/unsubscribe" => "customers#unsubscribe"
  patch "/customers/withdraw" => "customers#withdraw"
  delete "/cart_items/destroy_all" => "cart_items#destroy_all", as: "destroy_all_cart_items"
  resources :cart_items, only: [:index, :update, :destroy, :create]
  post "/orders/confirm" => "orders#confirm"
  get "/orders/complete" => "orders#complete"
  resources :orders, only: [:new, :create, :show, :index]
  resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  get "/search" => "items#search"

end

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
namespace :admin do
  get '/' => "homes#top"
  resources :items, only: [:index, :new, :create, :show, :edit, :update]
  resources :genres, only: [:index, :create, :edit, :update]
  resources :customers, only: [:index, :show, :edit, :update]
  resources :orders, only: [:show, :update]
  get "orders/customers/:id" => "orders#index"
  resources :order_details, only:[:update]
  get "/search" => "items#search"

end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :order_details, dependent: :destroy
  has_many :carts, dependent: :destroy
  has_many :orders, through: :order_details

  has_many :cart_items
  has_many :order_details

  has_one_attached :image
  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.png')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
  # refileの記述
  # attachment :image

  validates :introduction, presence: true
  validates :name, presence: true
  validates :price, presence: true, numericality: { only_integer: true }
  validates :is_active, inclusion: {in: [true, false]}

  # 消費税
  def taxin_price
    price*1.1
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  before_action :authenticate_admin!

  def index
    @items = Item.all.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash.now[:success] = "商品の新規登録が完了しました。"
      redirect_to admin_item_path(@item)
    else
      flash.now[:danger] = "商品の登録内容に不備があります。"
      render "new"
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash.now[:success] = "商品詳細の変更が完了しました。"
      redirect_to admin_item_path(@item)
    else
      flash.now[:danger] = "商品詳細の変更内容に不備があります。"
      render "edit"
    end
  end


 private

 def item_params
   params.require(:item).permit(:image, :name, :introduction, :price, :genre_id ,:is_active)
 end

end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/_item_errors.erb
<% if item.errors.any? %>
  <%= item.errors.count %>prohibited this obj from being saved:
  <% item.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

app/views/admin/items/edit.html.erb
<!-- 商品編集ページ WF5ページ目 -->

<div class="container">
  <div class="row"  style="margin-top:25px;">
    <div class="col-sm-8 px-sm-0 offset-sm-1">
      <h4>商品編集</h4>
    </div>
  </div>
   <div class="row ml-5">
    <div class="col-sm-10 px-sm-0 mx-auto">
      <%= form_with model: @item, url: admin_item_path, local: true do |f| %>
      <table class="table table-borderless text-secondary">
        <tr>
          <div class="form-group">
            <th><%= f.label :商品画像 %></th>
            <th><%= f.file_field :image, accept:"image/*" %></th>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <th><%= f.label :商品名 %></th>
            <td><%= f.text_field :name, placeholder:"商品名" %></td>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <th><%= f.label :商品説明 %></th>
            <td><%= f.text_area :introduction, size: "50x5", placeholder:"ここに説明文を記述します" %></td>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <th><%= f.label :ジャンル %></th>
            <td><%= f.collection_select :genre_id, Genre.all, :id, :name, :prompt => "--選択してください--" %></td>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <th><%= f.label :税抜価格 %></th>
            <td><%= f.text_field :price, placeholder:"1000" %>円</td>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <th><%= f.label :販売ステータス %></th>
            <td><%= f.radio_button :is_active, true, checked: true %>
            <%= f.label :is_active, "販売中" %>
            <%= f.radio_button :is_active, false %>
            <%= f.label :is_active, "販売中止" %></td>
          </div>
        </tr>
        <tr>
          <div class="form-action">
            <td><%= f.submit "変更を保存", class:"btn btn-success" %></td>
          </div>
        </tr>
      </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<!-- 商品一覧ページ WF2ページ目 -->

<div class="container px-5 px-sm-0">
  <div class="row" style="margin-top:25px;">
    <div class="col-sm-8 px-sm-0 offset-sm-1">
      <h4>商品一覧</h4>
    </div>
    <div class="col-sm-2 px-sm-0 text-right mb-2">
      <%= link_to new_admin_item_path do %>
        <button type="button" class="btn btn-outline-dark btn-sm">＋</button>
      <% end %>
    </div>
    <div class="col-sm-10 px-sm-0 mx-auto mb-5">
      <table class="table table-hover">
        <thead class="table-active">
          <tr>
            <th>商品ID</th>
            <th>商品名</th>
            <th>税抜価格</th>
            <th>ジャンル</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <% @items.each do |item| %>
        <tbody>
          <div class="float start">
          <tr>
            <td><%= item.id %></td>
            <td><%= link_to item.name,admin_item_path(item), class: "text-dark font-weight-bold" %></td>
            <td><%= item.price.to_s(:delimited) %></td>
            <td><%= item.genre.name %></td>
            <td>
              <% if item.is_active == true %>
               <p class="text-success font-weight-bold">販売中</p>
              <% else %>
               <p class="text-danger font-weight-bold">販売停止中</p>
              <% end %>
            </td>
          </tr>
          </div>
        </tbody>
        <% end %>
      </table>
        <%= paginate @items %>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<!-- 商品新規登録ページ WF3ページ目 -->

<div class="container">
  <div class="row">
   <div class="col-sm-8 px-sm-0 offset-sm-1">
     <h4>商品新規登録</h4>
     <%= render 'item_errors', item: @item %>
   </div>
  </div>

  <div class="row">
   <div class="col-sm-10 px-sm-0 mx-auto mb-5">
     <%= form_with model: @item, url: admin_items_path,local:true do |f| %>
     <table class="table table-borderless">
       <tr>
         <div class="form-group">
           <th><%= f.label :商品画像 %></th>
           <th><%= f.file_field :image, accept:"image/*" %></th>
         </div>
       </tr>
       <tr>
         <div class="form-group">
           <th><%= f.label :商品名 %></th>
           <td><%= f.text_field :name, size:"50x5", placeholder:"商品名" %></td>
         </div>
       </tr>
       </br>
       <tr>
         <div class="form-group">
           <th><%= f.label :商品説明 %></th>
           <td><%= f.text_area :introduction, size:"54x5", placeholder:"ここに説明文を記述します" %></td>
         </div>
       </tr>
       <tr>
         <div class="form-group">
           <th><%= f.label :ジャンル%></th>
           <td><%= f.collection_select :genre_id, Genre.all, :id,:name,{prompt: "--選択してください--"} %></td>
         </div>
       </tr>
       </br>
       <tr>
         <div class="form-group">
           <th><%= f.label:税抜価格 %></th>
           <td><%= f.text_field :price, placeholder:"1000" %>円</td>
         </div>
       </tr>
       <tr>
        <div class="form-group">
          <th><%= f.label :販売ステータス %></th>
          <td><%= f.radio_button :is_active, true, checked: true %>
              <%= f.label :is_active, "販売中" %>
              <%= f.radio_button :is_active, false %>
              <%= f.label :is_active, "販売停止中" %>
          </td>
        </div>
       </tr>
       <tr>
        <div class="form-action">
          <td><%= f.submit "新規登録", class:"btn btn-success" %></td>
        </div>
       </tr>
      <% end %>
      </table>
    </div>
   </div>
 </div>

app/views/admin/items/show.html.erb
<!-- 商品詳細ページ WF4ページ目 -->

<div class="container">
  <div class="row" style="margin-top:25px;">
    <div class="col-sm-8 px-sm-0 offset-sm-1">
      <h4>商品詳細</h4>
    </div>
  </div>
  <div class="row">
     <div class="col-sm-6 text-right mx-auto mb-5">
       <%= image_tag @item.get_image, size:"300x300"%>
     </div>
     <div class="col-sm-6 mx-auto">
     <table class="table table-borderless text-secondary d-flex text-align">
       <tr>
         <th>商品名</th>
         <td><%= @item.name %></td>
       </tr>
       <tr>
         <th>商品説明</th>
         <td><%= @item.introduction %></td>
       </tr>
       <tr>
         <th>ジャンル</th>
         <td><%= @item.genre.name %></td>
       </tr>
       <tr>
         <th>税込価格<br>(税抜価格)</th>
         <td><%= (@item.price*1.1).floor.to_s(:delimited) %>(<%= (@item.price).floor.to_s(:delimited) %>)円</td>
       </tr>
       <tr>
         <th>販売ステータス</th>
         <td><% if @item.is_active == true %>
            <p class="text-success font-weight-bold">販売中</p>
            <% else %>
            <p class="text-danger font-weight-bold">販売停止中</p>
            <% end %>
         </td>
       </tr>
     </table>
     </div>
   </div>
  </div>
  <div class="row">
    <div class="col-12">
      <div class="text-center">
      <%= link_to "編集する",edit_admin_item_path(@item), class:"btn btn-success" %>
      </div>
    </div>
  </div>
</div>

<!-- refileの記述 -->
      <!--%= attachment_image_tag @image, :image, size:'250x250', fallback: 'no_image.jpg',size: "250x250" % -->