config/routes.rb
Rails.application.routes.draw do
# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# scope module URLを変えない/ファイル構成だけ指定のパスにする
scope module: :public do
  root to: "homes#top"
  get "/about" => "homes#about"
  resources :items, only: [:index, :show]

  resource :customers, only: [:edit, :update]
  get "/customers/my_page" => "customers#show"
  get "/customers" => "customers#show"
  get "/customers/information/edit" => "customers#edit"
  patch "customers/information" => "customers#update"
  get "/customers/unsubscribe" => "customers#unsubscribe"
  patch "/customers/withdraw" => "customers#withdraw"
  delete "/cart_items/destroy_all" => "cart_items#destroy_all", as: "destroy_all_cart_items"
  resources :cart_items, only: [:index, :update, :destroy, :create]
  post "/orders/confirm" => "orders#confirm"
  get "/orders/complete" => "orders#complete"
  resources :orders, only: [:new, :create, :show, :index]
  resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  get "/search" => "items#search"

end

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
namespace :admin do
  get '/' => "homes#top"
  resources :items, only: [:index, :new, :create, :show, :edit, :update]
  resources :genres, only: [:index, :create, :edit, :update]
  resources :customers, only: [:index, :show, :edit, :update]
  resources :orders, only: [:show, :update]
  get "orders/customers/:id" => "orders#index"
  resources :order_details, only:[:update]
  get "/search" => "items#search"

end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  
  enum status: { wait_payment: 0, confirm_payment: 1, making: 2, preparing_ship: 3, finish_prepare: 4 }
  enum payment_method: { credit_card: 0, transfer: 1 }
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def index
    @customer = Customer.find(params[:id])
    @orders = @customer.orders
    @orders = @customer.orders.order(created_at: :desc).page(params[:page]).per(10)
  end
  
  def show
    @order_details = OrderDetail.where(order_id: params[:id])
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order_details = OrderDetail.where(order_id: params[:id])
    if @order.update(order_params)
      @order_details.update_all(making_status: 1) if @order.status == "confirm_payment"
    # ①注文ステータスが「入金確認」とき、製作ステータスを全て「製作待ち」に更新する
    end
      redirect_to admin_order_path(@order)
  end

  private

  def order_params
    params.require(:order).permit(:status)
  end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row' style="margin-top:25px;">
    <div class="col-sm-8 px-sm-0 offset-sm-1">
      <h4><%= @customer.last_name %><%= @customer.first_name %>さんの注文履歴</h4>
    </div>
    <div class="col-sm-10 px-sm-0 mx-auto mb-5">
    <table class='table table-hover'>
        <thead class="table-active">
          <tr>
            <th>購入日時</th>
            <th>注文個数</th>
            <th>注文ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |order| %>
          <tr>
            <td>
              <%= link_to  admin_order_path(order.id), class: "text-dark font-weight-bold" do %>
                <%=  l order.created_at %>
              <% end %>
            </td>
            <td><%= order.order_details.sum(:amount) %></td>
            <td><%= order.status_i18n %></td>
          </tr>
          <% end %>
        </tbody>
    </table>
    <div class="mx-auto font-weight-bold" style="width:200px;">
      <%= paginate @orders %>
    </div>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class='container px-5 px-sm-0'>

  <div class='row px-3' style="margin-top:25px;">
    <div class="col-sm-10 px-sm-0 offset-sm-1">
      <h4>注文履歴詳細</h4>
    </div>
    <div class="col-7 px-sm-0 mb-5 offset-sm-1">
    <table class='table table-borderbottom table-sm'>
      <tbody>
        <tr>
          <th>購入者</th>
          <td><%= link_to @order.customer.last_name + @order.customer.first_name, admin_customer_path(@order.customer) %></td>
        </tr>
        <tr>
          <th>注文日</th>
          <td><%= l @order.created_at, format: :short %></td>
        </tr>
        <tr>
          <th>配送先</th>
          <td>〒<%= @order.postal_code %>  <%= @order.address %></br><%= @order.name %></td>
        </tr>
        <tr>
          <th>支払い方法</th>
          <td><%= @order.payment_method_i18n %></td>
        </tr>
        <tr>
          <th>注文ステータス</th>
          <td>
          <% if @order.status == 1 %>
            <%= form.select :making_status == 1, class: "production_status-select" %>
          <% else %>
            <%= form_with model: @order, url: admin_order_path, method: :patch, local: true do |f| %>
              <%= f.select :status, Order.statuses_i18n.invert, class: "status" %>
              <%= f.submit "更新" , class: 'btn btn-info' %>
            <% end %>
          <% end %>
          </td>
        </tr>
      </tbody>
    </table>
    </div>
  </div>

  <div class='row'>
    <div class='col-8 px-sm-0'>
      <table class='table'>
        <thead class="table-active">
          <tr>
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @order_details.each do |order_detail| %>
          <tr>
            <td><%= order_detail.item.name %></td>
            <td><%= (order_detail.item.taxin_price).floor.to_s(:delimited) %></td>
            <td><%= order_detail.amount %></td>
            <td><%= (order_detail.item.taxin_price * order_detail.amount).floor.to_s(:delimited) %></td>
            <td>
              <%= form_with model: order_detail , url: admin_order_detail_path(order_detail.id), method: :patch , local: true do |f| %>
                <%= f.select :making_status, OrderDetail.making_statuses_i18n.invert %>
                <%= f.submit "更新", class: "btn btn-success" %>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-3 pl-2 px-sm-0">
      </br></br></br></br>
      <table class='table table-borderless text-right'>
        <tbody>
          <tr>
            <th>商品合計</th>
            <td> ¥<%= (@order.total_payment - @order.shipping_cost).to_s(:delimited)%></td>
          </tr>
          <tr>
            <th>送料</th>
            <td>¥<%= @order.shipping_cost %></td>
          </tr>
          <tr>
            <th>請求金額合計</th>
            <td>¥<%= @order.total_payment.to_s(:delimited) %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

</div>