config/routes.rb
Rails.application.routes.draw do
# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# scope module URLを変えない/ファイル構成だけ指定のパスにする
scope module: :public do
  root to: "homes#top"
  get "/about" => "homes#about"
  resources :items, only: [:index, :show]

  resource :customers, only: [:edit, :update]
  get "/customers/my_page" => "customers#show"
  get "/customers" => "customers#show"
  get "/customers/information/edit" => "customers#edit"
  patch "customers/information" => "customers#update"
  get "/customers/unsubscribe" => "customers#unsubscribe"
  patch "/customers/withdraw" => "customers#withdraw"
  delete "/cart_items/destroy_all" => "cart_items#destroy_all", as: "destroy_all_cart_items"
  resources :cart_items, only: [:index, :update, :destroy, :create]
  post "/orders/confirm" => "orders#confirm"
  get "/orders/complete" => "orders#complete"
  resources :orders, only: [:new, :create, :show, :index]
  resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  get "/search" => "items#search"

end

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
namespace :admin do
  get '/' => "homes#top"
  resources :items, only: [:index, :new, :create, :show, :edit, :update]
  resources :genres, only: [:index, :create, :edit, :update]
  resources :customers, only: [:index, :show, :edit, :update]
  resources :orders, only: [:show, :update]
  get "orders/customers/:id" => "orders#index"
  resources :order_details, only:[:update]
  get "/search" => "items#search"

end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


end

app/models/genre.rb
class Genre < ApplicationRecord
 has_many :items, dependent: :destroy

 validates :name, presence: true
 
 
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  before_action :authenticate_admin!

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path, notice: "ジャンルを追加しました。"
    else
      flash.now[:danger] = "予期せぬエラーが発生しました。"
      @genres = Genre.all
      render 'index'
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path, notice: "ジャンルを更新しました。"
    else
      flash.now[:danger] = "予期せぬエラーが発生しました。"
      render 'edit'
    end
  end

 private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/_genre_errors.html.erb
<% if genre.errors.any? %>
  <%= genre.errors.count %>prohibited this obj from being saved:
  <% genre.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

app/views/admin/genres/_genre_index.html.erb
<% genres.each do |genre| %>
<tr>
  <td><%= genre.name %></td>
  <td><%= link_to "編集する", edit_admin_genre_path(genre.id), class: "btn btn-success" %></td>
</tr>
<% end %>

app/views/admin/genres/_genre_sidber.html.erb
<table class="genre-table table table-bordered table-hover">
  <thead class="genre-thead">
    <tr>
      <th class="active">ジャンル検索</th>
    </tr>
  </thead>

  <tbody>
    <% genres.each do |genre| %>
      <tr>
        <td>
          <%= link_to items_path(genre_id: genre.id) do %>
            <%= genre.name %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
 </table>

app/views/admin/genres/_genre_sidebar.html.erb
<table class="genre-table table table-bordered table-hover">
  <thead class="table-active">
    <tr>
      <th>ジャンル検索</th>
    </tr>
  </thead>

  <tbody>
    <% genres.each do |genre| %>
      <tr>
        <td>
          <%= link_to items_path(genre_id: genre.id), class: "text-dark" do %>
            <%= genre.name %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
 </table>

app/views/admin/genres/edit.html.erb
<!-- ジャンル編集ページ WF7ページ目 -->

<div class="container px-5 px-sm-0">
  <div class="row" style="margin-top:25px; margin-bottom:200px;">
    <div class="col-sm-8 px-sm-0 offset-sm-1">
      <h4>ジャンル編集</h4>
      <%= form_with model: @genre, url: admin_genre_path, class: "genre_edit_form", local:true do |f| %>
        <table class ="table table-borderless">
          <th><%= f.label :ジャンル名 %></th>
          <th><%= f.text_field :name, class: "genre-edit-field" %></th>
          <th><%= f.submit "変更を保存する", class: "btn btn-success" %></th>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<!-- ジャンル一覧・追加ページ WF6ページ目 -->

<div class="container px-5 px-sm-0">
  <div class="row" style="margin-top:25px;">
    <div class="col-sm-8 px-sm-0 offset-sm-1">
      <h4 class="genre-head">ジャンル一覧・追加</h4>
      <%= render 'genre_errors', genre: @genre %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-8 px-sm-0 offset-sm-1">
      <%= form_with model: @genre, url: admin_genres_path do |f| %>
      <table class="table table-borderless">
        <tr>
          <div class="form-group">
            <th><%= f.label :ジャンル名 %></th>
            <th><%= f.text_field :name, placeholder:"ジャンル名" %></th>
            <th><%= f.submit "新規登録", class: "btn btn-success" %></th>
          </div>
        </tr>
      </table>
      <% end %>
    </div>
  </div>

　<div class="row px-5">
　  <div class="col-md-3">
　    <table class='table'>
　      <thead class="thead-light text-center">
　        <tr>
            <th>ジャンル</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <%= render 'genre_index', genres: @genres %>
        </tbody>
      </table>
    </div>
  </div>
</div>