config/routes.rb
Rails.application.routes.draw do
# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# scope module URLを変えない/ファイル構成だけ指定のパスにする
scope module: :public do
  root to: "homes#top"
  get "/about" => "homes#about"
  resources :items, only: [:index, :show]

  resource :customers, only: [:edit, :update]
  get "/customers/my_page" => "customers#show"
  get "/customers" => "customers#show"
  get "/customers/information/edit" => "customers#edit"
  patch "customers/information" => "customers#update"
  get "/customers/unsubscribe" => "customers#unsubscribe"
  patch "/customers/withdraw" => "customers#withdraw"
  delete "/cart_items/destroy_all" => "cart_items#destroy_all", as: "destroy_all_cart_items"
  resources :cart_items, only: [:index, :update, :destroy, :create]
  post "/orders/confirm" => "orders#confirm"
  get "/orders/complete" => "orders#complete"
  resources :orders, only: [:new, :create, :show, :index]
  resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  get "/search" => "items#search"

end

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
namespace :admin do
  get '/' => "homes#top"
  resources :items, only: [:index, :new, :create, :show, :edit, :update]
  resources :genres, only: [:index, :create, :edit, :update]
  resources :customers, only: [:index, :show, :edit, :update]
  resources :orders, only: [:show, :update]
  get "orders/customers/:id" => "orders#index"
  resources :order_details, only:[:update]
  get "/search" => "items#search"

end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  validates :customer_id, :name, :address, presence: true
  
  
  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  
  # 税込価格✕個数
  def sum_price
    item.taxin_price*quantity
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :addresses, dependent: :destroy
         has_many :cart_items, dependent: :destroy
         has_many :orders, dependent: :destroy

         validates :first_name, :last_name, :first_name_kana, :last_name_kana, :address, :telephone_number, presence: true

  def full_name
    [last_name, first_name].join(' ')
  end

  def full_name_kana
    [last_name_kana, first_name_kana].join(' ')
  end

  def active_for_authentication?
    super && (is_deleted == false)
  end
  
  
end

app/models/genre.rb
class Genre < ApplicationRecord
 has_many :items, dependent: :destroy

 validates :name, presence: true
 
 
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :order_details, dependent: :destroy
  has_many :carts, dependent: :destroy
  has_many :orders, through: :order_details

  has_many :cart_items
  has_many :order_details

  has_one_attached :image
  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.png')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
  # refileの記述
  # attachment :image

  validates :introduction, presence: true
  validates :name, presence: true
  validates :price, presence: true, numericality: { only_integer: true }
  validates :is_active, inclusion: {in: [true, false]}

  # 消費税
  def taxin_price
    price*1.1
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  
  enum status: { wait_payment: 0, confirm_payment: 1, making: 2, preparing_ship: 3, finish_prepare: 4 }
  enum payment_method: { credit_card: 0, transfer: 1 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  
  enum making_status: { impossible_manufacture:0, waiting_manufacture:1, manufacturing:2, finish:3 }
  
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  before_action :authenticate_admin!

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path, notice: "ジャンルを追加しました。"
    else
      flash.now[:danger] = "予期せぬエラーが発生しました。"
      @genres = Genre.all
      render 'index'
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path, notice: "ジャンルを更新しました。"
    else
      flash.now[:danger] = "予期せぬエラーが発生しました。"
      render 'edit'
    end
  end

 private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

before_action :authenticate_admin!

  def top
    @orders = Order.all
    @orders = Order.all.order(created_at: :desc).page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  before_action :authenticate_admin!

  def index
    @items = Item.all.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash.now[:success] = "商品の新規登録が完了しました。"
      redirect_to admin_item_path(@item)
    else
      flash.now[:danger] = "商品の登録内容に不備があります。"
      render "new"
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash.now[:success] = "商品詳細の変更が完了しました。"
      redirect_to admin_item_path(@item)
    else
      flash.now[:danger] = "商品詳細の変更内容に不備があります。"
      render "edit"
    end
  end


 private

 def item_params
   params.require(:item).permit(:image, :name, :introduction, :price, :genre_id ,:is_active)
 end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

 

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def after_sign_in_path_for(resource)
     public_customer_path
  end
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_footer.html.erb
<footer class="py-5 bg-footer blockquote-footer font-weight-light">
  <div class="bg-secondary nav-link text-light">
    <div class="container">
      <div class="row text-center text-xs-center text-sm-left text-md-left ">
  	    <div class="col-xs-12 col-sm-8 col-md-3">
  	  	  <h6><strong>メールマガジン登録</strong></h6>
  	  	  <form>
		        <input type="email" class="mail-box" placeholder="メールアドレスを入力"><br>
		        <input type="submit" class="btn mail-magazine text-light" value="登録する">
		      </form>
        </div>

        <div class="col-xs-12 col-sm-8 col-md-6">
          <h6>ONLINE STORE</h6>
          <div class="row">
            <div class="col-6">
              <ul class="list-unstyled quick-links">
			          <li><%= link_to "TOP", root_path, class: 'nav-link text-light' %></li>
			          <li><%= link_to "マイページ", customers_path, class: 'nav-link text-light' %></li>
			          <li><%= link_to "商品一覧", items_path, class: 'nav-link text-light' %></li>
			          <li><%= link_to "特定商取引法に基づく表記", root_path, class: 'nav-link text-light' %></li>
			          <li><%= link_to "プライバシーポリシー", root_path, class: 'nav-link text-light' %></li>
			        </ul>
		        </div>
            <div class="col-6">
              <ul class="list-unstyled quick-links">
           	    <li><%= link_to "ご利用ガイド", root_path, class: 'nav-link text-light' %></li>
           	    <div class="footer-lists">
           	      <li><%= link_to "お支払いについて", root_path, class: 'nav-link text-light' %></li>
           	      <li><%= link_to "配送について", root_path, class: 'nav-link text-light' %></li>
           	      <li><%= link_to "よくある質問", root_path, class: 'nav-link text-light' %></li>
           	    </div>
              </ul>
            </div>
          </div>
        </div>

        <div class="col-xs-12 col-sm-8 col-md-3">
	        <h6>ABOUT</h6>
      	    <ul class="list-unstyled quick-links">
	            <li><%= link_to "NAGANO CAKEについて", about_path, class: 'nav-link text-light' %></li>
	            <li><%= link_to "会社概要", root_path, class: 'nav-link text-light' %></li>
	            <li><%= link_to "メディア・プレス", root_path, class: 'nav-link text-light' %></li>
	            <li><%= link_to "スタッフ募集", root_path, class: 'nav-link text-light' %></li>
	            <li><%= link_to "お問い合わせ", root_path, class: 'nav-link text-light' %></li>
	          </ul>
   	    </div>
	    </div>

	   <div class="row">
	     <div class="col text-center">
	       <p>© 2022,NAGANO CAKE, © 2022 Team KaitenSushi Japan</p>
	     </div>
	   </div>
	  </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="bg-secondary text-monospace">
  <nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container ">
      <%= link_to root_path do %>
        <%= image_tag 'logo.png', size: "150x50" %>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">

        <!--adminログイン時のヘッダー-->
            <% if admin_signed_in? %>
              <li>
                <%= link_to "商品一覧", admin_items_path, class: 'nav-link text-light' %>
              </li>
              <li >
                <%= link_to "会員一覧", admin_customers_path, class: 'nav-link text-light'  %>
              </li>
              <li>
                <%= link_to "注文履歴一覧", admin_path, class: 'nav-link text-light' %>
              </li>
              <li>
                <%= link_to "ジャンル一覧", admin_genres_path, class: 'nav-link text-light' %>
              </li>
              <li>
                <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-light' %>
              </li>
              <li class="nav-link">
                <%= form_with url: items_path, method: :get, local: true do |f| %>
                  <%= f.text_field :content, placeholder: '🍰🍰🍰  search  🍰🍰🍰' %>
                  <%= f.submit '🔎'%>
                <% end %>
              </li>

            <!--customersログイン時のヘッダー-->
            <% elsif customer_signed_in? %>
              <li class= "nav-link text-light">
                ようこそ！ <%= link_to customers_path, class: "text-white font-weight-bold" do %>
                <%= current_customer.last_name %><%= current_customer.first_name %>
                <% end %>
                さん
              </li>
              <li>
                <%= link_to "マイページ", customers_path, class: 'nav-link text-light' %>
              </li>
              <li>
                <%= link_to "商品一覧", items_path, class: 'nav-link text-light' %>
              </li>
              <li>
                <%= link_to "カート", cart_items_path, class: 'nav-link text-light' %>
              </li>
              <li>
                <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'nav-link text-light' %>
              </li>
              <li class="nav-link">
                <%= form_with url: items_path, method: :get, local: true do |f| %>
                  <%= f.text_field :content, placeholder: '🍰🍰🍰  search  🍰🍰🍰' %>
                  <%= f.submit '🔎'%>
                <% end %>
              </li>
            <% else %>
            <!--ログイン前時のヘッダー-->
              <li>
                <%= link_to "About", about_path, class: 'nav-link text-light' %>
              </li>
              <li>
                <%= link_to "商品一覧", items_path, class: 'nav-link text-light' %>
              </li>
              <li>
                <%= link_to "新規登録", new_customer_registration_path, data: {"turbolinks" => false}, class: 'nav-link text-light' %>
              </li>
              <li>
                <%= link_to "ログイン", new_customer_session_path, class: 'nav-link text-light' %>
              </li>
              <li class="nav-link">
                <%= form_with url: items_path, method: :get, local: true do |f| %>
                  <%= f.text_field :content, placeholder: '🍰🍰🍰  search  🍰🍰🍰' %>
                  <%= f.submit '🔎'%>
                <% end %>
              </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCAKE</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
      <main class="text-secondary">
        <%= yield %>
      </main>
    <%= render 'layouts/footer' %>
  </body>
</html>